---
- name: Copying a file
  hosts: all
  become: yes
  tasks:
  - name: copying a file
    copy:
      src: /home/ansadmin/index.html
      dest: /home/ansadmin/index.html
      mode: 0755
      owner: venkat
